GET http://localhost:5000/users

###
//Daftar user all
POST  http://localhost:5000/users
Content-Type: application/json

{
    "nama": "Fauzun Atabiq, S.T., M.Cs",
    "password": "123456",
    "confPassword": "123456",
    "role": "4"
}

###
//Tambah char
POST  http://localhost:5000/character
Content-Type: application/json

{
    "name": "Poli",
    "characterClass": "2",
    "code": "2",
    "weapon": "3",
    "company":"1",
    "squad":"Artemis"
}

###
//edit char
PATCH   http://localhost:5000/character/2
Content-Type: application/json

{
    "name": "Poli",
    "characterClass": "2",
    "code": "2",
    "weapon": "3",
    "company":"1",
    "squad":"Artemis"
}

###
/// get char by id
GET http://localhost:5000/character/2

###
/// get char all
GET http://localhost:5000/character

###
/// login admin
POST  http://localhost:5000/login
Content-Type: application/json

{
   
    "nama": "Admin",
    "password": "123456"
    
}

###
/// login user
POST  http://localhost:5000/login
Content-Type: application/json

{
   
    "nama": "Fahri Efendi",
    "password": "123456"
    
}

###
DELETE  http://localhost:5000/logout

###
GET   http://localhost:5000/me

###
DELETE http://localhost:5000/character/2
